version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fastapi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password  # ✅ modern plugin

      TZ: ${TZ}

    ports:
      - "3307:3306"
    volumes:
      - fastapi_database_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - ./code:/app/code:ro  # read-only bind mount for code (safer)
    # No command needed; ENTRYPOINT from Dockerfile is used

volumes:
  fastapi_database_data:
